trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python39:
      python.version: '3.9'
    Python312:
      python.version: '3.12'
    Python315:
      python.version: '3.15'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r dev-requirements.txt
  displayName: 'Install dependencies'

- script: |
    black --check desafe.py tests
  displayName: 'check source code formatting'

- script: |
    tox
  displayName: 'tox testing'
